before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    binary: attestation
    ldflags: -X github.com/liatrio/gh-trusted-builds-attestations/build.Version={{.Version}}
    env:
     - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
