name: app
on:
  push:
    branches:
      - *
    tags:
      - v*.*.*

env:
  GO_VERSION: "1.20"

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Detect Workflow
        id: detect-workflow
        uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow-js@v1.6.0
      - name: Sigstore Setup
        uses: sigstore/scaffolding/actions/setup@v0.6.4
        with:
          version: "v0.6.4"
      - name: Run Tests
        env:
          KEYLESS_ISSUER: "https://token.actions.githubusercontent.com"
          KEYLESS_SUBJECT: ${{ github.server_url }}/${{ github.repository }}/${{ steps.detect-workflow.outputs.workflow }}@${{ steps.detect-workflow.outputs.ref }}
          # the attestation tool expects a value for GITHUB_TOKEN, but interactions with the GitHub API are replayed from fixtures
          GITHUB_TOKEN: "invalid"
        run: |
          ./hack/test-run.sh

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
